[package]
name = "troodon"
version = "0.1.0"
edition = "2024"

[dependencies]
# Наш Event Loop (runtime). Вмикаємо "full", щоб мати все: таймери, TCP, signal handling.
tokio = { version = "1", features = ["full"] }

# Наш Proxy Framework.
# Features:
# - "lb": Load Balancer (базові можливості проксі)
# - "proxy": HTTP Proxy
# - "openssl": підтримка TLS/SSL
pingora = { version = "0.7.0", features = ["lb", "proxy", "openssl"] }
# Для логування (щоб бачити, що відбувається в консолі)
async-trait = "0.1"
# === Logging (The "Zap" replacement) ===
# tracing - це ядро (фасад)
tracing = "0.1"
# tracing-subscriber - це реалізація (пише в stdout, JSON, etc.)
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
# log - потрібен для сумісності, бо Pingora пише в старий 'log' crate
log = "0.4"

# === Configuration (YAML Parsing) ===
# serde - це фреймворк серіалізації (як encoding/json в Go)
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

# === Error Handling ===
# Щоб простіше повертати помилки (Result<T, anyhow::Error>)
anyhow = "1.0"
arc-swap = "1.8.2"
matchit = "0.9.1"
http = "1.4.0"
pingora-limits = "0.7.0"
prometheus = "0.13"
bytes = "1.11.1"
openssl = { version = "0.10.75", features = ["v102", "v110"] }
